source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins do
  gem 'jekyll-paginate'
  gem 'kramdown'
  gem 'pygments.rb'
  gem 'rake'  # I should probably add this here.
  gem 'octopress-video-tag'
  # gem 'wdm', '>= 0.10' if Gem.win_platform?
end
